server-ip=127.0.0.1
server-port=25567
motd=RPG World
max-players=180
view-distance=8
simulation-distance=6
difficulty=normal
online-mode=false
enforce-secure-profile=false
enable-rcon=false
enable-query=false
sync-chunk-writes=false
