proxies:
  velocity:
    enabled: true
    online-mode: true
    secret: b6dbcd359f8c33bcb763e42906da1643af1631d97836e7ce00a1b83239e4a5ae
player-auto-save:
  max-per-tick: 10
  rate: 6000
spam-limiter:
  incoming-packet-threshold: 250
  recipe-spam-increment: 1
  recipe-spam-limit: 20
  tab-spam-increment: 1
  tab-spam-limit: 500
scoreboards:
  save-empty-scoreboard-teams: false
  track-plugin-scoreboards: false
spark:
  enabled: true
  enable-immediately: false
