server-ip=127.0.0.1
server-port=25569
motd=Boss Arena
max-players=80
view-distance=6
simulation-distance=4
difficulty=hard
online-mode=false
enforce-secure-profile=false
enable-rcon=false
enable-query=false
sync-chunk-writes=false
