server-ip=127.0.0.1
server-port=25568
motd=Dungeon Instances
max-players=120
view-distance=6
simulation-distance=4
difficulty=normal
online-mode=false
enforce-secure-profile=false
enable-rcon=false
enable-query=false
sync-chunk-writes=false
