proxies:
  velocity:
    enabled: true
    online-mode: true
    secret: 648bd8266cc644c2fdaad059851119f9581016bd0fbb80e23f611508373ccc3c
player-auto-save:
  max-per-tick: 10
  rate: 6000
spam-limiter:
  incoming-packet-threshold: 250
  recipe-spam-increment: 1
  recipe-spam-limit: 20
  tab-spam-increment: 1
  tab-spam-limit: 500
scoreboards:
  save-empty-scoreboard-teams: false
  track-plugin-scoreboards: false
spark:
  enabled: true
  enable-immediately: false
