server-ip=127.0.0.1
server-port=25570
motd=World Events
max-players=150
view-distance=7
simulation-distance=5
difficulty=normal
online-mode=false
enforce-secure-profile=false
enable-rcon=false
enable-query=false
sync-chunk-writes=false
