server-ip=127.0.0.1
server-port=25566
motd=RPG Lobby
max-players=250
view-distance=6
simulation-distance=4
difficulty=easy
online-mode=false
enforce-secure-profile=false
enable-rcon=false
enable-query=false
sync-chunk-writes=false
