#!/usr/bin/env python3
from __future__ import annotations

import argparse
import secrets
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "configs"
PROXY = ROOT / "proxy"

def load_yaml(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)

def dump_yaml(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(payload, handle, sort_keys=False, allow_unicode=True)

def get_or_create_secret(secret_path: Path, rotate: bool) -> str:
    if rotate or not secret_path.exists():
        secret_path.parent.mkdir(parents=True, exist_ok=True)
        secret = secrets.token_hex(32)
        secret_path.write_text(secret + "\n", encoding="utf-8")
        return secret
    return secret_path.read_text(encoding="utf-8").strip()

def render_velocity(network: dict) -> str:
    proxy = network["proxy"]
    servers = network["servers"]
    advanced = proxy["advanced"]
    query = proxy["query"]

    def q(value):
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, int):
            return str(value)
        return '"' + str(value).replace('"', '\\"') + '"'

    lines = [
        '# Generated by ops/render_network.py',
        'config-version = "2.7"',
        f'bind = {q(proxy["bind"])}',
        f'motd = {q(proxy["motd"])}',
        f'show-max-players = {q(proxy["show_max_players"])}',
        f'online-mode = {q(proxy["online_mode"])}',
        f'force-key-authentication = {q(proxy["force_key_authentication"])}',
        f'prevent-client-proxy-connections = {q(proxy["prevent_client_proxy_connections"])}',
        f'player-info-forwarding-mode = {q(proxy["player_info_forwarding_mode"]).upper()}',
        f'forwarding-secret-file = {q(proxy["forwarding_secret_file"])}',
        'announce-forge = false',
        f'kick-existing-players = {q(proxy["kick_existing_players"])}',
        f'ping-passthrough = {q(proxy["ping_passthrough"]).upper()}',
        f'sample-players-in-ping = {q(proxy["sample_players_in_ping"])}',
        f'enable-player-address-logging = {q(proxy["enable_player_address_logging"])}',
        '',
        '[servers]',
    ]

    for name, data in servers.items():
        lines.append(f'{name} = {q(data["address"])}')

    lines.extend(['try = ['])
    for server_name in proxy["try"]:
        lines.append(f'  {q(server_name)},')
    lines.extend([']', '', '[forced-hosts]', '', '[advanced]'])

    mapping = {
        'compression_threshold': 'compression-threshold',
        'compression_level': 'compression-level',
        'login_ratelimit': 'login-ratelimit',
        'connection_timeout': 'connection-timeout',
        'read_timeout': 'read-timeout',
        'haproxy_protocol': 'haproxy-protocol',
        'tcp_fast_open': 'tcp-fast-open',
        'bungee_plugin_message_channel': 'bungee-plugin-message-channel',
        'show_ping_requests': 'show-ping-requests',
        'failover_on_unexpected_server_disconnect': 'failover-on-unexpected-server-disconnect',
        'announce_proxy_commands': 'announce-proxy-commands',
        'log_command_executions': 'log-command-executions',
        'log_player_connections': 'log-player-connections',
        'accepts_transfers': 'accepts-transfers',
        'enable_reuse_port': 'enable-reuse-port',
        'command_rate_limit': 'command-rate-limit',
        'forward_commands_if_rate_limited': 'forward-commands-if-rate-limited',
        'kick_after_rate_limited_commands': 'kick-after-rate-limited-commands',
        'tab_complete_rate_limit': 'tab-complete-rate-limit',
        'kick_after_rate_limited_tab_completes': 'kick-after-rate-limited-tab-completes',
    }
    for key, toml_key in mapping.items():
        lines.append(f'{toml_key} = {q(advanced[key])}')

    lines.extend(['', '[query]'])
    for key, value in query.items():
        lines.append(f'{key} = {q(value)}')

    lines.append('')
    return '\n'.join(lines)

def render_server_properties(server_name: str, server_data: dict) -> str:
    host, port = server_data["address"].split(":")
    props = {
        'server-ip': host,
        'server-port': port,
        'motd': server_data['motd'],
        'max-players': server_data['max_players'],
        'view-distance': server_data['view_distance'],
        'simulation-distance': server_data['simulation_distance'],
        'difficulty': server_data['difficulty'],
        'online-mode': 'false',
        'enforce-secure-profile': 'false',
        'enable-rcon': 'false',
        'enable-query': 'false',
        'sync-chunk-writes': 'false',
    }
    return '\n'.join(f'{k}={v}' for k, v in props.items()) + '\n'

def render_paper_global(secret: str) -> dict:
    return {
        'proxies': {
            'velocity': {
                'enabled': True,
                'online-mode': True,
                'secret': secret,
            }
        },
        'player-auto-save': {
            'max-per-tick': 10,
            'rate': 6000,
        },
        'spam-limiter': {
            'incoming-packet-threshold': 250,
            'recipe-spam-increment': 1,
            'recipe-spam-limit': 20,
            'tab-spam-increment': 1,
            'tab-spam-limit': 500,
        },
        'scoreboards': {
            'save-empty-scoreboard-teams': False,
            'track-plugin-scoreboards': False,
        },
        'spark': {
            'enabled': True,
            'enable-immediately': False,
        },
    }

def render_legacy_paper_yml(server_data: dict) -> dict:
    return {
        'settings': {
            'view-distance': server_data['view_distance'],
        }
    }

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--rotate-secret', action='store_true')
    args = parser.parse_args()

    network = load_yaml(CONFIG / 'network.yml')
    secret_path = PROXY / network['proxy']['forwarding_secret_file']
    secret = get_or_create_secret(secret_path, args.rotate_secret)

    (PROXY / 'velocity.toml').write_text(render_velocity(network), encoding='utf-8')

    for server_name, server_data in network['servers'].items():
        server_dir = ROOT / server_name
        server_dir.mkdir(parents=True, exist_ok=True)
        (server_dir / 'server.properties').write_text(render_server_properties(server_name, server_data), encoding='utf-8')
        dump_yaml(server_dir / 'config' / 'paper-global.yml', render_paper_global(secret))
        dump_yaml(server_dir / 'paper.yml', render_legacy_paper_yml(server_data))

    print('RENDER_OK')
    print(f'SECRET_PATH={secret_path}')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
